/* The Daniels-Gilbert port, held to the Python module it was ported from.
 *
 * THIS FILE IS WHY THE PORT IS ALLOWED TO EXIST. The repo's rule against a
 * second implementation is really a rule against an UNPINNED one -- every
 * sanctioned port here has a check behind it, and this is that check. The
 * fixture is generated by `tests/fixtures/build_pace_model_reference.py`
 * directly from `scripts/pace-models/daniels_gilbert.py`, so a coefficient
 * changed on the Python side and not here fails the web suite.
 *
 * IT IS A COMMITTED FIXTURE AND NOT A LIVE COMPARISON, because Node cannot call
 * Python -- `tests/test_web_segregation.py` refuses a process from either side
 * -- and because a committed one runs on a checkout with no
 * `scripts/pace-models/` at all. Same shape as `fitness-reference.json`.
 *
 * IT LIVES UNDER `src/test/` SO THAT IT TRAVELS. `export_demo.py` copies the
 * app from `git ls-files web` and nothing else, so a fixture under `tests/`
 * would be missing from the demo repository and this file would fail to
 * RESOLVE its import there -- an error three repositories from the edit that
 * caused it, and one a green suite here structurally cannot see. Where it is,
 * the demo's own CI runs this same pin against the copied port.
 *
 * 1e-9 RATHER THAN EXACT. Both sides are IEEE 754 doubles running the same
 * operations in the same order, so they agree bit for bit in practice; the
 * tolerance is for the JSON round trip of the fixture itself, which is where a
 * last-digit difference could legitimately enter. A tolerance this tight cannot
 * hide a wrong coefficient -- the smallest of them moves a prediction by whole
 * seconds.
 */

import { describe, expect, it } from "vitest";

import REFERENCE from "@/test/paceModelReference.json";
import {
  MILE_METRES,
  checkVo2max,
  oxygenCost,
  paceForDuration,
  raceSeconds,
  sustainableFraction,
  velocityAt,
  vvo2maxSecPerMi,
} from "./danielsGilbert";

/** Every case must actually be compared. A fixture section that arrived empty
 *  would make its `forEach` a no-op and its case a pass -- the vacuous-guard
 *  shape this repo has paid for twice. */
function nonEmpty<T>(rows: T[], what: string): T[] {
  expect(rows.length, `${what} has no cases`).toBeGreaterThan(0);
  return rows;
}

describe("the coefficients are the published ones", () => {
  it("matches the Python module value for value", () => {
    const c = REFERENCE.coefficients;
    // Read back through the functions rather than re-exporting the constants:
    // what matters is the value the arithmetic uses, and a constant exported
    // for a test to read can be right while the expression using it is wrong.
    expect(MILE_METRES).toBe(c.MILE_METRES);
    // vo2(0+) -> the intercept, and the linear and quadratic terms fall out of
    // two more evaluations. Three points determine a quadratic exactly.
    const v0 = oxygenCost(1e-9);
    expect(v0).toBeCloseTo(c.COST_INTERCEPT, 6);
    const a = (oxygenCost(2) - 2 * oxygenCost(1) + oxygenCost(1e-12)) / 1;
    expect(a).toBeCloseTo(2 * c.COST_QUADRATIC, 9);
    expect(oxygenCost(1) - c.COST_INTERCEPT - c.COST_QUADRATIC).toBeCloseTo(
      c.COST_LINEAR,
      9,
    );
    // F(t) -> the floor as t grows without bound.
    expect(sustainableFraction(1e6)).toBeCloseTo(c.FRAC_FLOOR, 12);
  });
});

describe("every reference case reproduces", () => {
  it("oxygen_cost", () => {
    for (const r of nonEmpty(REFERENCE.oxygen_cost, "oxygen_cost")) {
      expect(oxygenCost(r.v)).toBeCloseTo(r.vo2, 9);
    }
  });

  it("sustainable_fraction", () => {
    for (const r of nonEmpty(
      REFERENCE.sustainable_fraction,
      "sustainable_fraction",
    )) {
      expect(sustainableFraction(r.minutes)).toBeCloseTo(r.f, 9);
    }
  });

  it("velocity_at", () => {
    for (const r of nonEmpty(REFERENCE.velocity_at, "velocity_at")) {
      expect(velocityAt(r.vo2)).toBeCloseTo(r.v, 9);
    }
  });

  it("vvo2max_sec_per_mi", () => {
    for (const r of nonEmpty(
      REFERENCE.vvo2max_sec_per_mi,
      "vvo2max_sec_per_mi",
    )) {
      expect(vvo2maxSecPerMi(r.vo2max)).toBeCloseTo(r.sec_per_mi, 9);
    }
  });

  it("race_seconds, across 15 anchors and 8 distances", () => {
    for (const r of nonEmpty(REFERENCE.race_seconds, "race_seconds")) {
      expect(
        raceSeconds(r.vo2max, r.distance_m),
        `${r.vo2max} over ${r.distance_m} m`,
      ).toBeCloseTo(r.seconds, 9);
    }
  });

  it("pace_for_duration, the tempo range's two ends", () => {
    for (const r of nonEmpty(
      REFERENCE.pace_for_duration,
      "pace_for_duration",
    )) {
      expect(paceForDuration(r.vo2max, r.duration_seconds)).toBeCloseTo(
        r.sec_per_mi,
        9,
      );
    }
  });
});

describe("the anchor the whole model is calibrated on", () => {
  it("55.57 inverts to the athlete's recorded 339.9 s/mi", () => {
    /* `thresholds.json -> vvo2max_calibration` records this pair as an
     * OBSERVATION, from before the model was implemented. It reproducing to the
     * decimal is the evidence that Runalyze's vVO2max is this same inversion,
     * and it is the one number in this file that is not merely "the port agrees
     * with the Python" -- it is "both agree with the record". */
    expect(vvo2maxSecPerMi(55.57)).toBeCloseTo(339.9, 1);
  });
});

describe("the guards", () => {
  it.each([19.9, 90.1, NaN, Infinity])("refuses VO2max %s", (v) => {
    expect(() => checkVo2max(v)).toThrow(/out of range/);
    expect(() => raceSeconds(v, 5000)).toThrow(/out of range/);
  });

  it.each([20, 55.57, 90])("accepts VO2max %s at the edges", (v) => {
    expect(() => checkVo2max(v)).not.toThrow();
  });

  it.each([99, 500_001])("refuses distance %s", (d) => {
    expect(() => raceSeconds(55, d)).toThrow(/distance out of range/);
  });

  it.each([0, -1])("refuses non-positive velocity %s", (v) => {
    expect(() => oxygenCost(v)).toThrow(/must be positive/);
  });

  it.each([0, -1])("refuses non-positive duration %s", (m) => {
    expect(() => sustainableFraction(m)).toThrow(/must be positive/);
    expect(() => paceForDuration(55, m)).toThrow(/must be positive/);
  });

  it("refuses a non-positive oxygen cost", () => {
    expect(() => velocityAt(0)).toThrow(/must be positive/);
  });
});

describe("the shape of the curves", () => {
  it("a longer race is always slower per mile", () => {
    const at = (d: number) => raceSeconds(56.81, d) / (d / MILE_METRES);
    const paces = [800, 1500, 3000, 5000, 10000, 21097.5, 42195].map(at);
    for (let i = 1; i < paces.length; i++) {
      expect(paces[i], `${i}`).toBeGreaterThan(paces[i - 1]);
    }
  });

  it("more fitness is always faster, at every distance", () => {
    for (const d of [800, 5000, 42195]) {
      expect(raceSeconds(60, d)).toBeLessThan(raceSeconds(55, d));
    }
  });

  it("F(t) is strictly decreasing and crosses 1.0 near eleven minutes", () => {
    let prev = Infinity;
    for (const m of [1, 2, 5, 10, 11, 12, 30, 60, 120]) {
      const f = sustainableFraction(m);
      expect(f).toBeLessThan(prev);
      prev = f;
    }
    expect(sustainableFraction(10)).toBeGreaterThan(1);
    expect(sustainableFraction(12)).toBeLessThan(1);
  });

  it("velocityAt inverts oxygenCost", () => {
    for (const v of [100, 200, 300, 450]) {
      expect(velocityAt(oxygenCost(v))).toBeCloseTo(v, 9);
    }
  });

  it("is deterministic -- the bisection returns the same bits twice", () => {
    for (const d of [800, 5000, 42195]) {
      expect(raceSeconds(56.81, d)).toBe(raceSeconds(56.81, d));
    }
  });
});
