import type { NextConfig } from "next";
import { PHASE_DEVELOPMENT_SERVER } from "next/constants";

/* GENERATED by scripts/export_demo.py in the private repo. Do not edit here.
 *
 * A STATIC EXPORT, because this mirror is served by GitHub Pages, which serves
 * files and runs nothing. `next build` renders the published records into
 * `out/` once; re-running the export and pushing is what updates the site.
 *
 * `basePath` is the repo name, since a project page is served from a sub-path.
 * `assetPrefix` is deliberately NOT set beside it -- Next already serves assets
 * from under `basePath`, and the config docs say as much: a custom asset prefix
 * is for a CDN and is the wrong tool for a sub-path.
 *
 * IT IS DROPPED IN DEVELOPMENT, which is why this file is a FUNCTION OF THE
 * PHASE rather than an object. A basePath applies to `next dev` too, so the
 * bare `http://localhost:3000` that Next prints on startup served its own 404
 * and the app was three hidden path segments away. The prefix is a property of
 * where this is HOSTED -- a project page under a repo name -- and nothing in
 * the app knows about it: one route, no `next/link`, and Next resolves assets
 * against whichever value is set. So the build keeps it and dev does not.
 *
 * The private repo's own next.config.ts has none of this. It runs a server,
 * reads the records per request, and is the one place the numbers can be
 * refreshed without a build.
 */
const nextConfig = (phase: string): NextConfig => ({
  output: "export",

  // Served from a sub-path in production, from the root in development.
  ...(phase === PHASE_DEVELOPMENT_SERVER ? {} : { basePath: "/training-demo" }),

  /* Pin the workspace root to THIS directory -- Turbopack otherwise walks up
   * for a lockfile and can land outside the repo entirely. */
  turbopack: {
    root: import.meta.dirname,
  },
});

export default nextConfig;
